name: lightnovelapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  advance_pdf_viewer: ^2.0.0  # Ensure this version is the latest
  provider: ^6.0.5
  path_provider: ^2.0.11
  flutter_pdfview: ^1.3.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Book1.jpg
    - assets/Book1.pdf
    - assets/Book2.jpg
    - assets/Book2.pdf
    - assets/Book3.jpg
    - assets/Book3.pdf
    - assets/header_image.jpg
